import type { NextPage } from 'next'
import Head from 'next/head'

import { Button, Container, Grid, TextField } from '@mui/material'
import { useRouter } from 'next/router'
import useRoom from '../../app/hooks/useRoom'
import React, { useState } from 'react'

const JoinRoom: NextPage = () => {
  const router = useRouter();
  const { joinRoom } = useRoom();
  const [playerName, setPlayerName] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const { roomID } = router.query;

  const handleSubmit = async (e: React.ChangeEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      const { myID: playerID } = await joinRoom(roomID as string, playerName);
      window.open(`/play/${ roomID }/${ playerID }`, "_self");
      setIsLoading(false);
    } catch (error) {
      alert("Joining room failed.");
      setIsLoading(false);
    }
  }

  const handlePlayerNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e || !e.target) {
      return;
    }

    setPlayerName(e.target.value);
  }

  return (
    <Container>
      <form onSubmit={handleSubmit} >
      <Grid
        container
        alignItems="stretch"
        direction="column"
        spacing={2}
        textAlign="center"
        color="white"
        >
        <Head>
          <title>Play Pusoy Dos</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Grid item>
          <h2>Room { roomID }</h2>
        </Grid>
        <Grid item>
          <TextField variant="filled" fullWidth placeholder="Enter your name" onChange={handlePlayerNameChange} />
        </Grid>
        <Grid item>
          <Button variant="contained" fullWidth type="submit" >Join room</Button>
        </Grid>
      </Grid>
      </form>
    </Container>
  )
}

export default JoinRoom
